// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920103817_DataProtectionKeys")]
    partial class DataProtectionKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Data.Appeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("รหัสภายในระบบ");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("เวลาที่ส่งคำถาม (UTC)");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasComment("รายการคะแนนที่ถาม (Items.Id)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("สถานะ: Open = รอครูตอบ · Answered = ครูตอบแล้ว · Closed = เสร็จสิ้น");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasComment("นักเรียนที่ถาม (Students.Id)");

                    b.Property<bool>("UnreadByStudent")
                        .HasColumnType("boolean")
                        .HasComment("นักเรียนยังไม่ได้อ่านข้อความล่าสุด (ใช้แสดง badge ฝั่งนักเรียน)");

                    b.Property<bool>("UnreadByTeacher")
                        .HasColumnType("boolean")
                        .HasComment("ครูยังไม่ได้อ่านข้อความล่าสุด (ใช้แสดง badge ฝั่งครู)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UnreadByTeacher");

                    b.ToTable("Appeals", t =>
                        {
                            t.HasComment("คำถามเรื่องคะแนนจากนักเรียน (หน้าเว็บเรียกว่า สอบถามคะแนน) · มีคำถามที่ยังไม่เสร็จสิ้นได้ครั้งละหนึ่งคำถามต่อรายการ");
                        });
                });

            modelBuilder.Entity("Api.Data.AppealMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("รหัสภายในระบบ");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppealId")
                        .HasColumnType("integer")
                        .HasComment("คำถาม (Appeals.Id)");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("เวลาที่ส่ง (UTC)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("ข้อความ (ไม่เกิน 2000 ตัวอักษร)");

                    b.Property<bool>("FromTeacher")
                        .HasColumnType("boolean")
                        .HasComment("true = ครูเขียน · false = นักเรียนเขียน");

                    b.HasKey("Id");

                    b.HasIndex("AppealId");

                    b.ToTable("AppealMessages", t =>
                        {
                            t.HasComment("ข้อความในคำถามเรื่องคะแนน (ทั้งคำถามของนักเรียนและคำตอบของครู)");
                        });
                });

            modelBuilder.Entity("Api.Data.AssessmentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("รหัสภายในระบบ");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer")
                        .HasComment("ห้องเรียน (Classrooms.Id)");

                    b.Property<decimal>("MaxScore")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasComment("คะแนนเต็ม (มากกว่า 0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("ชื่อรายการ · ในห้องเดียวกันห้ามซ้ำ");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("ลำดับการแสดง · น้อยขึ้นก่อน");

                    b.Property<bool>("TeacherOnly")
                        .HasColumnType("boolean")
                        .HasComment("true = เห็นเฉพาะครู นักเรียนไม่เห็นและสอบถามไม่ได้ (เช่น คะแนนดิบก่อนคิดเป็นคะแนนเก็บ)");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId", "Name")
                        .IsUnique();

                    b.ToTable("Items", t =>
                        {
                            t.HasComment("รายการที่ให้คะแนนในห้อง เช่น สอบกลางภาค เต็ม 20");

                            t.HasCheckConstraint("CK_Item_MaxScore", "\"MaxScore\" > 0");
                        });
                });

            modelBuilder.Entity("Api.Data.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("รหัสภายในระบบ");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("ชื่อห้อง เช่น ม.2/1 · ในภาคเรียนเดียวกันห้ามซ้ำ");

                    b.Property<int>("TermId")
                        .HasColumnType("integer")
                        .HasComment("ภาคเรียนที่ห้องนี้อยู่ (Terms.Id)");

                    b.HasKey("Id");

                    b.HasIndex("TermId", "Name")
                        .IsUnique();

                    b.ToTable("Classrooms", t =>
                        {
                            t.HasComment("ห้องเรียนในภาคเรียน เช่น ม.2/1 · นักเรียนในห้องดูที่ Enrollments");
                        });
                });

            modelBuilder.Entity("Api.Data.Enrollment", b =>
                {
                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer")
                        .HasComment("ห้องเรียน (Classrooms.Id)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasComment("นักเรียน (Students.Id)");

                    b.Property<int>("No")
                        .HasColumnType("integer")
                        .HasComment("เลขที่ในห้อง (1-999)");

                    b.HasKey("ClassroomId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments", t =>
                        {
                            t.HasComment("ตารางเชื่อมห้องกับนักเรียน: นักเรียนคนไหนอยู่ห้องไหน และเลขที่เท่าไหร่");
                        });
                });

            modelBuilder.Entity("Api.Data.Score", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasComment("รายการคะแนน (Items.Id)");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasComment("นักเรียน (Students.Id)");

                    b.Property<decimal?>("Value")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasComment("คะแนนที่ได้ · null = ยังไม่ได้กรอก · ห้ามเกินคะแนนเต็ม (ตรวจในแอป)");

                    b.HasKey("ItemId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Scores", t =>
                        {
                            t.HasComment("คะแนนของนักเรียนต่อรายการ · แก้ผ่านแอปเท่านั้น เพื่อให้มีประวัติใน ScoreAudits");

                            t.HasCheckConstraint("CK_Score_Value", "\"Value\" IS NULL OR \"Value\" >= 0");
                        });
                });

            modelBuilder.Entity("Api.Data.ScoreAudit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("รหัสภายในระบบ");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("เวลาที่แก้ (UTC)");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasComment("รายการที่ถูกแก้ (Items.Id · อาจถูกลบไปแล้ว)");

                    b.Property<decimal?>("NewValue")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasComment("คะแนนหลังแก้ · null = ล้างเป็นว่าง");

                    b.Property<decimal?>("OldValue")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasComment("คะแนนก่อนแก้ · null = ว่าง");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasComment("นักเรียนที่ถูกแก้คะแนน (Students.Id)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasComment("ครูที่แก้ (Teachers.Id · อาจถูกลบไปแล้ว)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId", "StudentId");

                    b.ToTable("ScoreAudits", t =>
                        {
                            t.HasComment("ประวัติการแก้คะแนนทุกครั้ง · ตั้งใจไม่มี FK ประวัติจะอยู่ต่อแม้ลบรายการหรือนักเรียนไปแล้ว");
                        });
                });

            modelBuilder.Entity("Api.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("รหัสภายในระบบ (ไม่ใช่รหัสนักเรียน)");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("ชื่อ");

                    b.Property<string>("GoogleSub")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("บัญชี Google ที่นักเรียนเชื่อมไว้ (Google subject id) · null = ยังไม่เคยเข้าสู่ระบบ");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("นามสกุล");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("ชื่อเล่น · ว่างได้");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("รหัสนักเรียนของโรงเรียน · ห้ามซ้ำ");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("คำนำหน้า เช่น เด็กหญิง · ว่างได้");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSub")
                        .IsUnique();

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.ToTable("Students", t =>
                        {
                            t.HasComment("นักเรียนทั้งโรงเรียน · หนึ่งคนมีแถวเดียวใช้ข้ามทุกภาคเรียน (อยู่ห้องไหนดูที่ Enrollments)");
                        });
                });

            modelBuilder.Entity("Api.Data.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("รหัสภายในระบบ");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("อีเมล Google ที่ใช้ล็อกอิน (ตัวพิมพ์เล็ก ห้ามซ้ำ)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("ชื่อที่แสดง · ว่างได้ ถ้าว่างระบบแสดงอีเมลแทน");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("สิทธิ์: Owner = ผู้ดูแลระบบ (เห็นข้อมูลครูทุกคน + เพิ่ม/ลบครู) · Teacher = ครู (เห็นเฉพาะภาคเรียนของตัวเอง)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Teachers", t =>
                        {
                            t.HasComment("ครูที่เข้าระบบได้ด้วย Google · ครูคนแรกมาจาก env TEACHER_EMAILS หลังจากนั้นเพิ่ม/ลบที่หน้า จัดการครู");
                        });
                });

            modelBuilder.Entity("Api.Data.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("รหัสภายในระบบ");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("เวลาที่สร้าง (UTC)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("ชื่อภาคเรียน เช่น 1/2569 · ครูคนเดียวกันห้ามซ้ำ");

                    b.Property<bool>("PublicScores")
                        .HasColumnType("boolean")
                        .HasComment("เปิดให้ดูคะแนนด่วนโดยไม่ต้องล็อกอิน (ห้อง + เลขที่ + รหัสนักเรียน) · true = เปิด");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasComment("ครูเจ้าของภาคเรียน (Teachers.Id)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId", "Name")
                        .IsUnique();

                    b.ToTable("Terms", t =>
                        {
                            t.HasComment("ภาคเรียน เช่น 1/2569 · เป็นของครูหนึ่งคน");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Api.Data.Appeal", b =>
                {
                    b.HasOne("Api.Data.AssessmentItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Api.Data.AppealMessage", b =>
                {
                    b.HasOne("Api.Data.Appeal", null)
                        .WithMany("Messages")
                        .HasForeignKey("AppealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Data.AssessmentItem", b =>
                {
                    b.HasOne("Api.Data.Classroom", "Classroom")
                        .WithMany("Items")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("Api.Data.Classroom", b =>
                {
                    b.HasOne("Api.Data.Term", "Term")
                        .WithMany("Classrooms")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Term");
                });

            modelBuilder.Entity("Api.Data.Enrollment", b =>
                {
                    b.HasOne("Api.Data.Classroom", "Classroom")
                        .WithMany("Enrollments")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Api.Data.Score", b =>
                {
                    b.HasOne("Api.Data.AssessmentItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Data.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Api.Data.Term", b =>
                {
                    b.HasOne("Api.Data.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Api.Data.Appeal", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Api.Data.Classroom", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Api.Data.Term", b =>
                {
                    b.Navigation("Classrooms");
                });
#pragma warning restore 612, 618
        }
    }
}
